"""Assemble single-file code.py bundles for the Lemma functions.

Lemma function bundles only ship code.py — sibling modules are NOT importable
(proven: `ModuleNotFoundError` on import). So we inline the lemma-map core
modules into one file per function. lemma-map/ stays the single source of truth;
re-run this whenever those modules change:

    python backend/forge-fn/build.py
"""
from __future__ import annotations

import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent
CORE = ROOT.parent / "lemma-map"


def strip_module(name: str) -> str:
    """Return a module's body with top-level imports (incl. multi-line) and the
    CLI main()/__main__ tail removed, so it can be concatenated into one file."""
    src = (CORE / f"{name}.py").read_text()
    lines = src.splitlines()
    out: list[str] = []
    i, n = 0, len(lines)
    while i < n:
        line = lines[i]
        if re.match(r"^def main\(", line) or re.match(r"^if __name__", line):
            break  # drop the CLI entrypoint entirely
        if re.match(r"^(import |from )", line):
            if "(" in line and ")" not in line:  # multi-line parenthesized import
                while i < n and ")" not in lines[i]:
                    i += 1
                i += 1
                continue
            i += 1
            continue
        out.append(line)
        i += 1
    return "\n".join(out).strip()


HEADER = '''#input_type_name: {inp}
#output_type_name: {out}
#function_name: {fn}
"""AUTO-GENERATED by backend/forge-fn/build.py — DO NOT EDIT.

Edit the source modules in backend/lemma-map/, then re-run build.py. The Lemma
function runtime only ships code.py, so the Forge core is inlined below.
"""
from __future__ import annotations

import base64
import hashlib
import json
import os
import re
import time
from contextlib import contextmanager
from typing import Any

import httpx
from lemma_sdk import FunctionContext, Pod
from lemma_sdk.errors import LemmaConnectionError, LemmaRateLimitError, LemmaServerError
from lemma_sdk.openapi_client.models.create_conversation_request import (
    CreateConversationRequest,
)
from pydantic import BaseModel

'''

BANNER = "\n\n# " + "=" * 70 + "\n# inlined from backend/lemma-map/{name}.py\n# " + "=" * 70 + "\n\n"

API_EXTRA = r'''

# ======================================================================
# Forge API dispatcher (ported from backend/main.py routes)
# ======================================================================
_ARCH_LAYERS = ("client", "api", "data", "integration", "infra")


def _node_slug(text):
    s = re.sub(r"[^a-z0-9]+", "-", (text or "").strip().lower()).strip("-")
    return s or "node"


def _unique_node_slug(text, existing):
    base = _node_slug(text)
    slug, i = base, 2
    while slug in existing:
        slug, i = f"{base}-{i}", i + 1
    return slug


def _rf_nodes(nodes):
    return [{
        "id": n.get("slug"),
        "type": "forge",
        "position": {"x": n.get("pos_x") or 0.0, "y": n.get("pos_y") or 0.0},
        "data": {
            "slug": n.get("slug"), "title": n.get("title"), "summary": n.get("summary"),
            "layer": n.get("layer"), "kind": n.get("kind"), "status": n.get("status"),
        },
    } for n in nodes]


def _rf_edges(edges):
    out = []
    for e in edges:
        s, t = e.get("source"), e.get("target")
        out.append({"id": e.get("id") or f"{s}->{t}", "source": s, "target": t})
    return out


def _load_project(pod, project_id):
    proj = retry(lambda: pod.records.get("projects", project_id))
    if not proj:
        raise ValueError(f"project {project_id} not found")
    nodes = list_all(pod, "nodes", project_id=project_id)
    edges = list_all(pod, "edges", project_id=project_id)
    tasks = sorted(list_all(pod, "tasks", project_id=project_id),
                   key=lambda t: t.get("priority", 0))
    return {
        "project": {"id": proj.get("id"), "name": proj.get("name"),
                    "status": proj.get("status"),
                    "design_locked": proj.get("design_locked"),
                    "summary": proj.get("summary"), "prompt": proj.get("prompt")},
        "graph": {"nodes": _rf_nodes(nodes), "edges": _rf_edges(edges)},
        "tasks": tasks,
    }


class ForgeApiInput(BaseModel):
    action: str
    project_id: str | None = None
    node_id: str | None = None
    slug: str | None = None
    question: str | None = None
    refresh: bool = False
    status: str | None = None
    name: str | None = None
    prompt: str | None = None
    layer: str | None = None
    kind: str | None = None
    title: str | None = None
    summary: str | None = None
    pos_x: float | None = None
    pos_y: float | None = None
    source: str | None = None
    target: str | None = None
    edge_id: str | None = None
    push: bool = False
    owner: str | None = None
    repo: str | None = None


class ForgeApiResult(BaseModel):
    ok: bool = True
    error: str | None = None
    code: int | None = None
    data: Any = None


def _dispatch(pod, d: "ForgeApiInput"):
    a = d.action
    if a == "projects":
        items = retry(lambda: pod.records.list(
            "projects", limit=100,
            sort=[{"field": "created_at", "direction": "desc"}])).to_dict()["items"]
        return {"projects": [{
            "id": p.get("id"), "name": p.get("name"), "status": p.get("status"),
            "design_locked": p.get("design_locked"), "created_at": p.get("created_at"),
        } for p in items]}
    if a == "project":
        return _load_project(pod, d.project_id)
    if a == "guidance":
        return guide_node(pod, d.project_id, d.node_id, d.question, refresh=d.refresh)
    if a == "node_status":
        return set_node_status(pod, d.project_id, d.node_id or d.slug, d.status)
    if a == "lock":
        return lock_design(pod, d.project_id)
    if a == "unlock":
        return unlock_design(pod, d.project_id)
    if a == "export":
        return export_repo(pod, d.project_id, owner=d.owner, repo=d.repo, push=d.push)
    if a == "digest":
        return build_digest(pod, d.project_id)
    if a == "create_project":
        proj = retry(lambda: pod.records.create("projects", {
            "name": d.name or "Untitled", "prompt": d.prompt or "",
            "status": "active", "design_locked": False, "summary": ""}))
        return {"project": {
            "id": proj.get("id"), "name": proj.get("name"), "status": proj.get("status"),
            "design_locked": proj.get("design_locked"), "created_at": proj.get("created_at")}}
    if a == "create_node":
        layer = (d.layer or "api").lower()
        if layer not in _ARCH_LAYERS:
            layer = "api"
        existing = {n.get("slug") for n in list_all(pod, "nodes", project_id=d.project_id)}
        slug = _unique_node_slug(d.title or d.kind or "node", existing)
        row = retry(lambda: pod.records.create("nodes", {
            "project_id": d.project_id, "slug": slug, "layer": layer,
            "kind": d.kind or "component", "title": d.title or slug,
            "summary": d.summary or "", "status": "designed",
            "pos_x": d.pos_x or 0.0, "pos_y": d.pos_y or 0.0}))
        return {"node": _rf_nodes([row])[0]}
    if a == "update_node":
        slug = d.slug or d.node_id
        rows = retry(lambda: pod.records.list("nodes", limit=1, filter=[
            {"field": "project_id", "op": "eq", "value": d.project_id},
            {"field": "slug", "op": "eq", "value": slug}])).to_dict()["items"]
        if not rows:
            raise ValueError(f"node '{slug}' not found in project {d.project_id}")
        patch = {}
        for f in ("title", "summary", "layer", "status", "pos_x", "pos_y"):
            v = getattr(d, f)
            if v is not None:
                patch[f] = v
        if patch.get("layer") and patch["layer"] not in _ARCH_LAYERS:
            patch["layer"] = "api"
        row = rows[0] if not patch else retry(
            lambda: pod.records.update("nodes", rows[0]["id"], patch))
        return {"node": _rf_nodes([row])[0]}
    if a == "delete_node":
        slug = d.slug or d.node_id
        nodes = list_all(pod, "nodes", project_id=d.project_id)
        target = next((n for n in nodes if n.get("slug") == slug), None)
        if not target:
            raise ValueError(f"node '{slug}' not found in project {d.project_id}")
        edges = list_all(pod, "edges", project_id=d.project_id)
        edge_ids = [e["id"] for e in edges
                    if e.get("source") == slug or e.get("target") == slug]
        tasks = list_all(pod, "tasks", project_id=d.project_id)
        task_ids = [t["id"] for t in tasks if t.get("node_id") == slug]
        if edge_ids:
            retry(lambda: pod.records.bulk_delete("edges", edge_ids))
        if task_ids:
            retry(lambda: pod.records.bulk_delete("tasks", task_ids))
        retry(lambda: pod.records.delete("nodes", target["id"]))
        return {"deleted": slug, "edges_removed": len(edge_ids),
                "tasks_removed": len(task_ids)}
    if a == "create_edge":
        s, t = (d.source or "").strip(), (d.target or "").strip()
        if not s or not t or s == t:
            raise ValueError("edge needs distinct source and target")
        slugs = {n.get("slug") for n in list_all(pod, "nodes", project_id=d.project_id)}
        if s not in slugs or t not in slugs:
            raise ValueError("both edge endpoints must be existing nodes")
        edges = list_all(pod, "edges", project_id=d.project_id)
        pairs = [(e.get("source"), e.get("target")) for e in edges]
        if (s, t) in pairs:
            raise ValueError("edge already exists")
        if not is_dag(slugs, pairs + [(s, t)]):
            raise ValueError("that connection would create a cycle")
        row = retry(lambda: pod.records.create(
            "edges", {"project_id": d.project_id, "source": s, "target": t}))
        return {"edge": _rf_edges([row])[0]}
    if a == "delete_edge":
        retry(lambda: pod.records.delete("edges", d.edge_id))
        return {"deleted": d.edge_id}
    if a == "relayout":
        relayout_project(pod, d.project_id)
        return _load_project(pod, d.project_id)
    raise ValueError(f"unknown action: {a}")


async def forge_api(ctx: FunctionContext, data: ForgeApiInput) -> ForgeApiResult:
    pod = Pod.from_env()
    try:
        configure_timeout(pod)
    except Exception:  # noqa: BLE001 — internals may differ in the function runtime
        pass
    try:
        return ForgeApiResult(ok=True, data=_dispatch(pod, data))
    except PermissionError as e:
        return ForgeApiResult(ok=False, error=str(e), code=409)
    except ValueError as e:
        return ForgeApiResult(ok=False, error=str(e), code=400)
    except Exception as e:  # noqa: BLE001
        return ForgeApiResult(ok=False, error=f"{type(e).__name__}: {e}", code=500)
'''

GEN_EXTRA = r'''

# ======================================================================
# Forge generation JOB (runs minutes -> async; browser polls the projects list)
# ======================================================================
class ForgeGenerateInput(BaseModel):
    prompt: str
    name: str | None = None


class ForgeGenerateResult(BaseModel):
    ok: bool = True
    error: str | None = None
    project_id: str | None = None
    counts: dict | None = None
    summary: str | None = None


async def forge_generate(ctx: FunctionContext, data: ForgeGenerateInput) -> ForgeGenerateResult:
    pod = Pod.from_env()
    try:
        configure_timeout(pod)
    except Exception:  # noqa: BLE001
        pass
    try:
        pid, nodes, edges, tasks, summary_md = generate_architecture(pod, data.prompt, data.name)
        return ForgeGenerateResult(
            ok=True, project_id=pid,
            counts={"nodes": len(nodes), "edges": len(edges), "tasks": len(tasks)},
            summary=summary_md)
    except Exception as e:  # noqa: BLE001
        return ForgeGenerateResult(ok=False, error=f"{type(e).__name__}: {e}")
'''


def assemble(fn: str, inp: str, out: str, modules: list[str], extra: str) -> str:
    parts = [HEADER.format(fn=fn, inp=inp, out=out)]
    for m in modules:
        parts.append(BANNER.format(name=m))
        parts.append(strip_module(m))
    parts.append(extra)
    return "\n".join(parts).rstrip() + "\n"


def main() -> None:
    api = assemble(
        "forge_api", "ForgeApiInput", "ForgeApiResult",
        ["_forge", "generate_architecture", "guide_node", "approvals",
         "export_repo", "digest"],
        API_EXTRA)
    gen = assemble(
        "forge_generate", "ForgeGenerateInput", "ForgeGenerateResult",
        ["_forge", "generate_architecture"],
        GEN_EXTRA)

    (ROOT / "functions" / "forge_api").mkdir(parents=True, exist_ok=True)
    (ROOT / "functions" / "forge_generate").mkdir(parents=True, exist_ok=True)
    (ROOT / "functions" / "forge_api" / "code.py").write_text(api)
    (ROOT / "functions" / "forge_generate" / "code.py").write_text(gen)
    print(f"wrote forge_api/code.py ({len(api.splitlines())} lines)")
    print(f"wrote forge_generate/code.py ({len(gen.splitlines())} lines)")


if __name__ == "__main__":
    main()
