#input_type_name: ForgeGenerateInput
#output_type_name: ForgeGenerateResult
#function_name: forge_generate
"""AUTO-GENERATED by backend/forge-fn/build.py — DO NOT EDIT.

Edit the source modules in backend/lemma-map/, then re-run build.py. The Lemma
function runtime only ships code.py, so the Forge core is inlined below.
"""
from __future__ import annotations

import base64
import hashlib
import json
import os
import re
import time
from contextlib import contextmanager
from typing import Any

import httpx
from lemma_sdk import FunctionContext, Pod
from lemma_sdk.errors import LemmaConnectionError, LemmaRateLimitError, LemmaServerError
from lemma_sdk.openapi_client.models.create_conversation_request import (
    CreateConversationRequest,
)
from pydantic import BaseModel




# ======================================================================
# inlined from backend/lemma-map/_forge.py
# ======================================================================


# backend/lemma-map/_forge.py — shared Forge core (one source of truth)
#
# Every step script (generate_architecture, guide_node, approvals, export_repo,
# digest) and the FastAPI BFF import from here so the proven agent/RAG/retry
# patterns live in exactly one place. Importable as a sibling module:
#   - run a step script with `python lemma-map/<file>.py` (its dir is on sys.path)
#   - the BFF adds `lemma-map/` to sys.path then `import _forge`
#
# NOTE (2026-06-30): the agent + RAG helpers below were proven live in
# smoke_infer.py and one earlier generate_architecture run. Everything that calls
# the Lemma server is UNVERIFIED against the new step modules only because Cloud
# was mid-outage during the build — the code paths are identical to what passed.



# Lemma Cloud intermittently returns nginx 503 / rate-limits / drops a connection;
# these are transient and safe to retry (the agent keeps running server-side).
TRANSIENT = (LemmaServerError, LemmaRateLimitError, LemmaConnectionError)

AGENT = "hello"           # starter agent wired to the org runtime (no personal key)
MODEL = "deepseek-v4-flash"  # flash model — much faster than the default minimax-m3
RUNTIME_PROFILE = "system:lemma"
KNOWLEDGE = "/knowledge"  # RAG corpus seeded by seed_knowledge.py
LAYERS = ("client", "api", "data", "integration", "infra")
# left -> right column order on the canvas: foundations left, user-facing right
LAYER_X = {"infra": 0, "data": 1, "integration": 2, "api": 3, "client": 4}
TERMINAL = {"COMPLETED", "FAILED", "STOPPED"}

# the SDK's default HTTP read timeout is 30s with no env override; agent
# generation routinely exceeds it, so we bump the live client to 5 min.
AGENT_TIMEOUT = 300.0


# ---------- pod lifecycle ----------
@contextmanager
def open_pod():
    """Yield a Pod from env config with the long agent timeout already applied.

    Use as `with open_pod() as pod:` in every script/endpoint so nobody forgets
    the 300s bump that the default 30s timeout would otherwise break.
    """
    with Pod.from_env() as pod:
        configure_timeout(pod)
        yield pod


def configure_timeout(pod: Pod, seconds: float = AGENT_TIMEOUT) -> None:
    pod.generated.get_httpx_client().timeout = httpx.Timeout(seconds)


# ---------- retry around transient Cloud blips ----------
def retry(fn, *, tries: int = 6, base: float = 3.0):
    last = None
    for i in range(tries):
        try:
            return fn()
        except TRANSIENT as exc:
            last = exc
            wait = base * (i + 1)
            print(f"  ⟳ transient ({type(exc).__name__}); retry in {wait:.0f}s")
            time.sleep(wait)
    raise last


# backwards-compatible alias (generate_architecture used the name `_retry`)
_retry = retry


# ---------- agent inference (single message -> text reply, async poll) ----------
def ask(pod: Pod, message: str, *, timeout: int = 300, title: str = "forge") -> str:
    """Send one message to the agent and return its final TEXT reply.

    Agents reply asynchronously: open a conversation, then poll messages until a
    non-user TEXT message appears (or the conversation reaches a terminal state).
    Tolerates transient blips during polling — the agent keeps running.
    """
    req = CreateConversationRequest.from_dict({
        "agent_name": AGENT,
        "title": title,
        "agent_runtime": {"model_name": MODEL, "profile_id": RUNTIME_PROFILE},
    })
    conv = retry(lambda: pod.conversations.create(req))
    cid = str(conv.id)
    retry(lambda: pod.conversations.send(cid, message))
    deadline = time.time() + timeout
    status = None
    while time.time() < deadline:
        try:
            status = pod.conversations.get(cid).to_dict().get("status")
            msgs = pod.conversations.messages(cid).to_dict()["items"]
        except TRANSIENT:
            time.sleep(4)  # blip during polling — agent still running, keep waiting
            continue
        answers = [
            m for m in msgs
            if m.get("role") != "user" and m.get("kind") == "TEXT" and m.get("text")
        ]
        if answers:
            return sorted(answers, key=lambda m: m["sequence"])[-1]["text"]
        if status in TERMINAL:
            break
        time.sleep(2)  # poll a touch faster so the reply is picked up sooner
    raise RuntimeError(f"agent gave no reply (last status={status})")


def split_reply(text: str):
    """Return (json_dict, summary_md) from a two-part reply, tolerating fences/order.

    The contract every Forge prompt uses: a ```json fenced object plus free-prose
    markdown around it. Keeping JSON parse-safe and prose separate avoids escaping
    bugs and keeps tokens low.
    """
    m = re.search(r"```(?:json)?\s*(\{.*?\})\s*```", text, re.DOTALL)
    if m:
        data = json.loads(m.group(1))
        summary_md = (text[: m.start()] + text[m.end():]).strip()
    else:  # no fence — grab the outermost {...}, rest is markdown
        start, end = text.find("{"), text.rfind("}")
        data = json.loads(text[start: end + 1])
        summary_md = (text[:start] + text[end + 1:]).strip()
    return data, summary_md


# ---------- grounding via files RAG ----------
def search_knowledge(pod: Pod, queries: list[str], *, budget: int = 1800, per_query: int = 2):
    """Run scoped HYBRID searches over /knowledge, dedupe, and cap to `budget` chars.

    Returns (context_text, source_paths). Shared by generate (architecture queries)
    and guide_node (node-specific queries).
    """
    seen: set = set()
    chunks: list[str] = []
    paths: list[str] = []
    used = 0
    for q in queries:
        hits = retry(lambda q=q: pod.files.search(
            q, scope_path=KNOWLEDGE, scope_mode="SUBTREE", search_method="HYBRID"
        )).to_dict()["items"]
        for h in hits[:per_query]:
            key = (h["path"], h.get("chunk_index"))
            if key in seen:
                continue
            seen.add(key)
            text = " ".join(h["content"].split())
            if used + len(text) > budget:
                text = text[: budget - used]
            chunks.append(f"[{h['path']}] {text}")
            if h["path"] not in paths:
                paths.append(h["path"])
            used += len(text)
            if used >= budget:
                break
        if used >= budget:
            break
    return "\n".join(chunks), paths


def ground(pod: Pod, prompt: str, *, budget: int = 900) -> str:
    """Architecture-time grounding — kept lean (fewer/smaller searches) for speed."""
    queries = [
        f"architecture, components, layers and tech stack for: {prompt}",
        "how to sequence an MVP build and write the backlog",
    ]
    context, _ = search_knowledge(pod, queries, budget=budget, per_query=1)
    return context


# ---------- records helpers (used across steps + BFF) ----------
def list_all(pod: Pod, table: str, *, project_id: str | None = None, limit: int = 500):
    """List records, optionally scoped to a project, with retry. Returns a list."""
    flt = [{"field": "project_id", "op": "eq", "value": project_id}] if project_id else None
    return retry(lambda: pod.records.list(table, limit=limit, filter=flt)).to_dict()["items"]


def find_node(pod: Pod, project_id: str, slug: str):
    """Return the node row for a slug within a project, or None."""
    rows = retry(lambda: pod.records.list("nodes", limit=500, filter=[
        {"field": "project_id", "op": "eq", "value": project_id},
        {"field": "slug", "op": "eq", "value": slug},
    ])).to_dict()["items"]
    return rows[0] if rows else None


# ======================================================================
# inlined from backend/lemma-map/generate_architecture.py
# ======================================================================


# backend/lemma-map/generate_architecture.py — Step 3: idea -> ArchGraph -> tables
# Run: source .venv/bin/activate && python lemma-map/generate_architecture.py "your product idea"
#
# Pipeline: ground (/knowledge RAG) -> pass1 decompose -> pass2 refine+tasks ->
# validate/repair DAG -> persist project/nodes/edges/tasks. Two-part contract
# (json fence + ## Build Summary markdown) and all agent/RAG/retry plumbing live
# in _forge.py; this file owns only the graph-shaping + persistence.
#
# STATUS: built + compiles; one earlier run succeeded (15 nodes). The current
# shape is UNVERIFIED end-to-end only because Cloud was mid-outage at build time.



# ---------- DAG validation / repair (Kahn's, slug-keyed; ported from main.py) ----------
def is_dag(slugs: set[str], edges: list[tuple[str, str]]) -> bool:
    adj = {s: [] for s in slugs}
    indeg = {s: 0 for s in slugs}
    for s, t in edges:
        if s not in slugs or t not in slugs:
            continue
        adj[s].append(t)
        indeg[t] += 1
    queue = [s for s, d in indeg.items() if d == 0]
    visited = 0
    while queue:
        n = queue.pop()
        visited += 1
        for nb in adj[n]:
            indeg[nb] -= 1
            if indeg[nb] == 0:
                queue.append(nb)
    return visited == len(slugs)


def acyclic_subset(slugs: set[str], edges: list[tuple[str, str]]):
    """Greedily keep edges that don't introduce a cycle; return (kept, dropped)."""
    kept: list[tuple[str, str]] = []
    dropped: list[tuple[str, str]] = []
    for s, t in edges:
        if s not in slugs or t not in slugs or s == t:
            dropped.append((s, t))
            continue
        if is_dag(slugs, kept + [(s, t)]):
            kept.append((s, t))
        else:
            dropped.append((s, t))
    return kept, dropped


# ---------- normalize the agent graph ----------
def normalize(graph: dict):
    nodes, seen_slugs = [], set()
    for n in graph.get("nodes", []):
        slug = str(n.get("id") or "").strip()
        if not slug or slug in seen_slugs:
            continue
        seen_slugs.add(slug)
        layer = str(n.get("layer") or "").strip().lower()
        if layer not in LAYERS:
            layer = "api"
        nodes.append({
            "slug": slug,
            "layer": layer,
            "title": str(n.get("title") or slug).strip(),
            "summary": str(n.get("summary") or "").strip(),
        })
    slugs = {n["slug"] for n in nodes}
    raw_edges = [
        (str(e.get("source") or "").strip(), str(e.get("target") or "").strip())
        for e in graph.get("edges", [])
    ]
    kept, dropped = acyclic_subset(slugs, raw_edges)
    tasks = []
    for t in graph.get("tasks", []) or []:
        node = str(t.get("node") or t.get("node_id") or "").strip()
        title = str(t.get("title") or "").strip()
        if node in slugs and title:
            tasks.append({"node": node, "title": title})
    if not tasks:  # fallback: one concrete first task per node
        tasks = [{"node": n["slug"], "title": f"Build {n['title']}"} for n in nodes]
    return nodes, kept, dropped, tasks


# ---------- layered canvas layout (barycenter crossing-reduction) ----------
COL_GAP = 400.0   # x distance between layers (node is 224px wide)
ROW_GAP = 340.0   # y distance between rows (node is ~277px tall — keep a clear gap)


def layout(nodes, edges=None):
    """Left→right layered layout (column per layer) with the rows inside each
    column ordered by the barycenter (mean) of their neighbours' rows, iterated a
    few times. This is the cheap Sugiyama ordering heuristic — it untangles edges
    so source→target stays readable without pulling in a layout dependency."""
    edges = edges or []
    # group slugs by their column (layer); preserve input order as the seed
    columns: dict[int, list[str]] = {}
    col_of: dict[str, int] = {}
    for n in nodes:
        c = LAYER_X.get(n["layer"], 5)
        columns.setdefault(c, []).append(n["slug"])
        col_of[n["slug"]] = c

    nbrs: dict[str, list[str]] = {n["slug"]: [] for n in nodes}
    for s, t in edges:
        if s in nbrs and t in nbrs:
            nbrs[s].append(t)
            nbrs[t].append(s)

    order_cols = sorted(columns)
    for _ in range(4):  # a few sweeps converge fast for these sizes
        for c in order_cols:
            rank = {slug: i for col in columns.values() for i, slug in enumerate(col)}
            def bary(slug: str) -> float:
                ns = nbrs.get(slug, [])
                return (sum(rank[m] for m in ns) / len(ns)) if ns else rank[slug]
            columns[c].sort(key=bary)

    pos = {}
    for c in order_cols:
        col = columns[c]
        # vertically center each column so the graph reads as a balanced band
        offset = -(len(col) - 1) * ROW_GAP / 2.0
        for row, slug in enumerate(col):
            pos[slug] = (c * COL_GAP, offset + row * ROW_GAP)
    return pos


# ---------- persist ----------
def persist(pod, name: str, prompt: str, nodes, edges, tasks, summary_md: str):
    project = retry(lambda: pod.records.create("projects", {
        "name": name,
        "prompt": prompt,
        "status": "active",
        "design_locked": False,
        "summary": summary_md,
    }))
    pid = project["id"]
    pos = layout(nodes, edges)
    node_rows = [{
        "project_id": pid,
        "slug": n["slug"],
        "layer": n["layer"],
        "kind": "component",
        "title": n["title"],
        "summary": n["summary"],
        "status": "designed",
        "pos_x": pos[n["slug"]][0],
        "pos_y": pos[n["slug"]][1],
    } for n in nodes]
    edge_rows = [{"project_id": pid, "source": s, "target": t} for s, t in edges]
    task_rows = [{
        "project_id": pid,
        "node_id": t["node"],
        "title": t["title"],
        "status": "todo",
        "approval_state": "none",
        "priority": i,
    } for i, t in enumerate(tasks)]
    retry(lambda: pod.records.bulk_create("nodes", node_rows))
    if edge_rows:
        retry(lambda: pod.records.bulk_create("edges", edge_rows))
    if task_rows:
        retry(lambda: pod.records.bulk_create("tasks", task_rows))
    return pid


# ---------- re-tidy an existing project's layout ----------
def relayout_project(pod, project_id: str):
    """Recompute + persist node positions for a project (the canvas "Tidy" action).
    Single source of truth for layout, shared with generation."""
    nodes = list_all(pod, "nodes", project_id=project_id)
    edges = list_all(pod, "edges", project_id=project_id)
    edge_pairs = [(e.get("source"), e.get("target")) for e in edges]
    node_lite = [{"slug": n.get("slug"), "layer": n.get("layer") or "api"} for n in nodes]
    pos = layout(node_lite, edge_pairs)
    updates = [{"id": n["id"], "pos_x": pos[n["slug"]][0], "pos_y": pos[n["slug"]][1]}
               for n in nodes if n.get("slug") in pos]
    if updates:
        retry(lambda: pod.records.bulk_update("nodes", updates))
    return len(updates)


# ---------- orchestration ----------
# A generator that yields {"stage", ...} progress events as it works, ending with a
# {"stage":"done", ...} carrying the result. The whole pipeline takes minutes (two
# LLM passes), so streaming these stages is what lets the UI show real progress and
# lets the client abort: if it disconnects, the consumer stops pulling and no later
# stage (including the persist) runs.
def generate_steps(pod, prompt: str, name: str | None = None):
    name = name or " ".join(prompt.split()[:6])[:60]

    yield {"stage": "grounding"}
    guidance = ground(pod, prompt)
    yield {"stage": "grounded", "chars": len(guidance)}

    # SINGLE agent pass: ask for the full map AND the first build tasks at once.
    # This used to be two sequential passes (decompose, then refine + tasks), which
    # roughly doubled the wall-clock time. The local normalize() below already
    # repairs the graph into a valid DAG and back-fills tasks, so the second LLM
    # round-trip was redundant — dropping it ~halves generation time with no node cap.
    yield {"stage": "decompose"}
    reply = ask(pod, (
        "You are a senior software architect. Using the GUIDANCE below, decompose the "
        "product idea into a FOCUSED system map AND its first build tasks in a SINGLE pass. "
        "Cover the CORE components across the relevant layers (client, api, data, "
        "integration, infra) — aim for about 8–14 nodes, the ones that matter, no filler. "
        "Keep every summary to ONE short clause.\n"
        "Output EXACTLY two parts and nothing else:\n"
        "1) a ```json fenced block of shape:\n"
        '{"nodes":[{"id":"kebab-slug","layer":"client|api|data|integration|infra",'
        '"title":"short name","summary":"one clear sentence"}],'
        '"edges":[{"source":"id","target":"id"}],'
        '"tasks":[{"node":"id","title":"first concrete build task"}]}\n'
        "   Rules: an edge means target depends on source; ids unique kebab-case; the graph "
        "MUST be a DAG (no cycles) and fully connected (no orphans); exactly 1 task per node.\n"
        "2) a markdown section starting with `## Build Summary`: a one-line overview, then "
        "one bullet per node `- **title** (layer) — what it does`, then a `Build first:` line.\n"
        f"\nIDEA: {prompt}\n\nGUIDANCE:\n{guidance}"
    ), title="generate-architecture")
    graph, summary_md = split_reply(reply)
    yield {"stage": "decomposed",
           "nodes": len(graph.get("nodes", [])), "edges": len(graph.get("edges", []))}

    # local pass: normalize layers, repair cycles into a DAG, back-fill tasks (no LLM call)
    yield {"stage": "refine"}
    nodes, edges, dropped, tasks = normalize(graph)
    assert nodes, "no nodes produced"
    assert is_dag({n["slug"] for n in nodes}, edges), "graph still cyclic after repair"

    yield {"stage": "persisting",
           "nodes": len(nodes), "edges": len(edges), "tasks": len(tasks)}
    pid = persist(pod, name, prompt, nodes, edges, tasks, summary_md)
    yield {"stage": "done", "project_id": pid, "nodes": nodes, "edges": edges,
           "tasks": tasks, "summary_md": summary_md}


def generate_architecture(pod, prompt: str, name: str | None = None):
    """Blocking convenience wrapper (CLI + non-streaming route) over generate_steps."""
    done = None
    for ev in generate_steps(pod, prompt, name):
        if ev["stage"] == "done":
            done = ev
        else:
            print(f"• {ev['stage']}" + (f" { {k: v for k, v in ev.items() if k != 'stage'} }"
                                         if len(ev) > 1 else ""))
    assert done, "generation produced no result"
    return (done["project_id"], done["nodes"], done["edges"],
            done["tasks"], done["summary_md"])


# ======================================================================
# Forge generation JOB (runs minutes -> async; browser polls the projects list)
# ======================================================================
class ForgeGenerateInput(BaseModel):
    prompt: str
    name: str | None = None


class ForgeGenerateResult(BaseModel):
    ok: bool = True
    error: str | None = None
    project_id: str | None = None
    counts: dict | None = None
    summary: str | None = None


async def forge_generate(ctx: FunctionContext, data: ForgeGenerateInput) -> ForgeGenerateResult:
    pod = Pod.from_env()
    try:
        configure_timeout(pod)
    except Exception:  # noqa: BLE001
        pass
    try:
        pid, nodes, edges, tasks, summary_md = generate_architecture(pod, data.prompt, data.name)
        return ForgeGenerateResult(
            ok=True, project_id=pid,
            counts={"nodes": len(nodes), "edges": len(edges), "tasks": len(tasks)},
            summary=summary_md)
    except Exception as e:  # noqa: BLE001
        return ForgeGenerateResult(ok=False, error=f"{type(e).__name__}: {e}")
