#input_type_name: ForgeApiInput
#output_type_name: ForgeApiResult
#function_name: forge_api
"""AUTO-GENERATED by backend/forge-fn/build.py — DO NOT EDIT.

Edit the source modules in backend/lemma-map/, then re-run build.py. The Lemma
function runtime only ships code.py, so the Forge core is inlined below.
"""
from __future__ import annotations

import base64
import hashlib
import json
import os
import re
import time
from contextlib import contextmanager
from typing import Any

import httpx
from lemma_sdk import FunctionContext, Pod
from lemma_sdk.errors import LemmaConnectionError, LemmaRateLimitError, LemmaServerError
from lemma_sdk.openapi_client.models.create_conversation_request import (
    CreateConversationRequest,
)
from pydantic import BaseModel




# ======================================================================
# inlined from backend/lemma-map/_forge.py
# ======================================================================


# backend/lemma-map/_forge.py — shared Forge core (one source of truth)
#
# Every step script (generate_architecture, guide_node, approvals, export_repo,
# digest) and the FastAPI BFF import from here so the proven agent/RAG/retry
# patterns live in exactly one place. Importable as a sibling module:
#   - run a step script with `python lemma-map/<file>.py` (its dir is on sys.path)
#   - the BFF adds `lemma-map/` to sys.path then `import _forge`
#
# NOTE (2026-06-30): the agent + RAG helpers below were proven live in
# smoke_infer.py and one earlier generate_architecture run. Everything that calls
# the Lemma server is UNVERIFIED against the new step modules only because Cloud
# was mid-outage during the build — the code paths are identical to what passed.



# Lemma Cloud intermittently returns nginx 503 / rate-limits / drops a connection;
# these are transient and safe to retry (the agent keeps running server-side).
TRANSIENT = (LemmaServerError, LemmaRateLimitError, LemmaConnectionError)

AGENT = "hello"           # starter agent wired to the org runtime (no personal key)
MODEL = "deepseek-v4-flash"  # flash model — much faster than the default minimax-m3
RUNTIME_PROFILE = "system:lemma"
KNOWLEDGE = "/knowledge"  # RAG corpus seeded by seed_knowledge.py
LAYERS = ("client", "api", "data", "integration", "infra")
# left -> right column order on the canvas: foundations left, user-facing right
LAYER_X = {"infra": 0, "data": 1, "integration": 2, "api": 3, "client": 4}
TERMINAL = {"COMPLETED", "FAILED", "STOPPED"}

# the SDK's default HTTP read timeout is 30s with no env override; agent
# generation routinely exceeds it, so we bump the live client to 5 min.
AGENT_TIMEOUT = 300.0


# ---------- pod lifecycle ----------
@contextmanager
def open_pod():
    """Yield a Pod from env config with the long agent timeout already applied.

    Use as `with open_pod() as pod:` in every script/endpoint so nobody forgets
    the 300s bump that the default 30s timeout would otherwise break.
    """
    with Pod.from_env() as pod:
        configure_timeout(pod)
        yield pod


def configure_timeout(pod: Pod, seconds: float = AGENT_TIMEOUT) -> None:
    pod.generated.get_httpx_client().timeout = httpx.Timeout(seconds)


# ---------- retry around transient Cloud blips ----------
def retry(fn, *, tries: int = 6, base: float = 3.0):
    last = None
    for i in range(tries):
        try:
            return fn()
        except TRANSIENT as exc:
            last = exc
            wait = base * (i + 1)
            print(f"  ⟳ transient ({type(exc).__name__}); retry in {wait:.0f}s")
            time.sleep(wait)
    raise last


# backwards-compatible alias (generate_architecture used the name `_retry`)
_retry = retry


# ---------- agent inference (single message -> text reply, async poll) ----------
def ask(pod: Pod, message: str, *, timeout: int = 300, title: str = "forge") -> str:
    """Send one message to the agent and return its final TEXT reply.

    Agents reply asynchronously: open a conversation, then poll messages until a
    non-user TEXT message appears (or the conversation reaches a terminal state).
    Tolerates transient blips during polling — the agent keeps running.
    """
    req = CreateConversationRequest.from_dict({
        "agent_name": AGENT,
        "title": title,
        "agent_runtime": {"model_name": MODEL, "profile_id": RUNTIME_PROFILE},
    })
    conv = retry(lambda: pod.conversations.create(req))
    cid = str(conv.id)
    retry(lambda: pod.conversations.send(cid, message))
    deadline = time.time() + timeout
    status = None
    while time.time() < deadline:
        try:
            status = pod.conversations.get(cid).to_dict().get("status")
            msgs = pod.conversations.messages(cid).to_dict()["items"]
        except TRANSIENT:
            time.sleep(4)  # blip during polling — agent still running, keep waiting
            continue
        answers = [
            m for m in msgs
            if m.get("role") != "user" and m.get("kind") == "TEXT" and m.get("text")
        ]
        if answers:
            return sorted(answers, key=lambda m: m["sequence"])[-1]["text"]
        if status in TERMINAL:
            break
        time.sleep(2)  # poll a touch faster so the reply is picked up sooner
    raise RuntimeError(f"agent gave no reply (last status={status})")


def split_reply(text: str):
    """Return (json_dict, summary_md) from a two-part reply, tolerating fences/order.

    The contract every Forge prompt uses: a ```json fenced object plus free-prose
    markdown around it. Keeping JSON parse-safe and prose separate avoids escaping
    bugs and keeps tokens low.
    """
    m = re.search(r"```(?:json)?\s*(\{.*?\})\s*```", text, re.DOTALL)
    if m:
        data = json.loads(m.group(1))
        summary_md = (text[: m.start()] + text[m.end():]).strip()
    else:  # no fence — grab the outermost {...}, rest is markdown
        start, end = text.find("{"), text.rfind("}")
        data = json.loads(text[start: end + 1])
        summary_md = (text[:start] + text[end + 1:]).strip()
    return data, summary_md


# ---------- grounding via files RAG ----------
def search_knowledge(pod: Pod, queries: list[str], *, budget: int = 1800, per_query: int = 2):
    """Run scoped HYBRID searches over /knowledge, dedupe, and cap to `budget` chars.

    Returns (context_text, source_paths). Shared by generate (architecture queries)
    and guide_node (node-specific queries).
    """
    seen: set = set()
    chunks: list[str] = []
    paths: list[str] = []
    used = 0
    for q in queries:
        hits = retry(lambda q=q: pod.files.search(
            q, scope_path=KNOWLEDGE, scope_mode="SUBTREE", search_method="HYBRID"
        )).to_dict()["items"]
        for h in hits[:per_query]:
            key = (h["path"], h.get("chunk_index"))
            if key in seen:
                continue
            seen.add(key)
            text = " ".join(h["content"].split())
            if used + len(text) > budget:
                text = text[: budget - used]
            chunks.append(f"[{h['path']}] {text}")
            if h["path"] not in paths:
                paths.append(h["path"])
            used += len(text)
            if used >= budget:
                break
        if used >= budget:
            break
    return "\n".join(chunks), paths


def ground(pod: Pod, prompt: str, *, budget: int = 900) -> str:
    """Architecture-time grounding — kept lean (fewer/smaller searches) for speed."""
    queries = [
        f"architecture, components, layers and tech stack for: {prompt}",
        "how to sequence an MVP build and write the backlog",
    ]
    context, _ = search_knowledge(pod, queries, budget=budget, per_query=1)
    return context


# ---------- records helpers (used across steps + BFF) ----------
def list_all(pod: Pod, table: str, *, project_id: str | None = None, limit: int = 500):
    """List records, optionally scoped to a project, with retry. Returns a list."""
    flt = [{"field": "project_id", "op": "eq", "value": project_id}] if project_id else None
    return retry(lambda: pod.records.list(table, limit=limit, filter=flt)).to_dict()["items"]


def find_node(pod: Pod, project_id: str, slug: str):
    """Return the node row for a slug within a project, or None."""
    rows = retry(lambda: pod.records.list("nodes", limit=500, filter=[
        {"field": "project_id", "op": "eq", "value": project_id},
        {"field": "slug", "op": "eq", "value": slug},
    ])).to_dict()["items"]
    return rows[0] if rows else None


# ======================================================================
# inlined from backend/lemma-map/generate_architecture.py
# ======================================================================


# backend/lemma-map/generate_architecture.py — Step 3: idea -> ArchGraph -> tables
# Run: source .venv/bin/activate && python lemma-map/generate_architecture.py "your product idea"
#
# Pipeline: ground (/knowledge RAG) -> pass1 decompose -> pass2 refine+tasks ->
# validate/repair DAG -> persist project/nodes/edges/tasks. Two-part contract
# (json fence + ## Build Summary markdown) and all agent/RAG/retry plumbing live
# in _forge.py; this file owns only the graph-shaping + persistence.
#
# STATUS: built + compiles; one earlier run succeeded (15 nodes). The current
# shape is UNVERIFIED end-to-end only because Cloud was mid-outage at build time.



# ---------- DAG validation / repair (Kahn's, slug-keyed; ported from main.py) ----------
def is_dag(slugs: set[str], edges: list[tuple[str, str]]) -> bool:
    adj = {s: [] for s in slugs}
    indeg = {s: 0 for s in slugs}
    for s, t in edges:
        if s not in slugs or t not in slugs:
            continue
        adj[s].append(t)
        indeg[t] += 1
    queue = [s for s, d in indeg.items() if d == 0]
    visited = 0
    while queue:
        n = queue.pop()
        visited += 1
        for nb in adj[n]:
            indeg[nb] -= 1
            if indeg[nb] == 0:
                queue.append(nb)
    return visited == len(slugs)


def acyclic_subset(slugs: set[str], edges: list[tuple[str, str]]):
    """Greedily keep edges that don't introduce a cycle; return (kept, dropped)."""
    kept: list[tuple[str, str]] = []
    dropped: list[tuple[str, str]] = []
    for s, t in edges:
        if s not in slugs or t not in slugs or s == t:
            dropped.append((s, t))
            continue
        if is_dag(slugs, kept + [(s, t)]):
            kept.append((s, t))
        else:
            dropped.append((s, t))
    return kept, dropped


# ---------- normalize the agent graph ----------
def normalize(graph: dict):
    nodes, seen_slugs = [], set()
    for n in graph.get("nodes", []):
        slug = str(n.get("id") or "").strip()
        if not slug or slug in seen_slugs:
            continue
        seen_slugs.add(slug)
        layer = str(n.get("layer") or "").strip().lower()
        if layer not in LAYERS:
            layer = "api"
        nodes.append({
            "slug": slug,
            "layer": layer,
            "title": str(n.get("title") or slug).strip(),
            "summary": str(n.get("summary") or "").strip(),
        })
    slugs = {n["slug"] for n in nodes}
    raw_edges = [
        (str(e.get("source") or "").strip(), str(e.get("target") or "").strip())
        for e in graph.get("edges", [])
    ]
    kept, dropped = acyclic_subset(slugs, raw_edges)
    tasks = []
    for t in graph.get("tasks", []) or []:
        node = str(t.get("node") or t.get("node_id") or "").strip()
        title = str(t.get("title") or "").strip()
        if node in slugs and title:
            tasks.append({"node": node, "title": title})
    if not tasks:  # fallback: one concrete first task per node
        tasks = [{"node": n["slug"], "title": f"Build {n['title']}"} for n in nodes]
    return nodes, kept, dropped, tasks


# ---------- layered canvas layout (barycenter crossing-reduction) ----------
COL_GAP = 400.0   # x distance between layers (node is 224px wide)
ROW_GAP = 340.0   # y distance between rows (node is ~277px tall — keep a clear gap)


def layout(nodes, edges=None):
    """Left→right layered layout (column per layer) with the rows inside each
    column ordered by the barycenter (mean) of their neighbours' rows, iterated a
    few times. This is the cheap Sugiyama ordering heuristic — it untangles edges
    so source→target stays readable without pulling in a layout dependency."""
    edges = edges or []
    # group slugs by their column (layer); preserve input order as the seed
    columns: dict[int, list[str]] = {}
    col_of: dict[str, int] = {}
    for n in nodes:
        c = LAYER_X.get(n["layer"], 5)
        columns.setdefault(c, []).append(n["slug"])
        col_of[n["slug"]] = c

    nbrs: dict[str, list[str]] = {n["slug"]: [] for n in nodes}
    for s, t in edges:
        if s in nbrs and t in nbrs:
            nbrs[s].append(t)
            nbrs[t].append(s)

    order_cols = sorted(columns)
    for _ in range(4):  # a few sweeps converge fast for these sizes
        for c in order_cols:
            rank = {slug: i for col in columns.values() for i, slug in enumerate(col)}
            def bary(slug: str) -> float:
                ns = nbrs.get(slug, [])
                return (sum(rank[m] for m in ns) / len(ns)) if ns else rank[slug]
            columns[c].sort(key=bary)

    pos = {}
    for c in order_cols:
        col = columns[c]
        # vertically center each column so the graph reads as a balanced band
        offset = -(len(col) - 1) * ROW_GAP / 2.0
        for row, slug in enumerate(col):
            pos[slug] = (c * COL_GAP, offset + row * ROW_GAP)
    return pos


# ---------- persist ----------
def persist(pod, name: str, prompt: str, nodes, edges, tasks, summary_md: str):
    project = retry(lambda: pod.records.create("projects", {
        "name": name,
        "prompt": prompt,
        "status": "active",
        "design_locked": False,
        "summary": summary_md,
    }))
    pid = project["id"]
    pos = layout(nodes, edges)
    node_rows = [{
        "project_id": pid,
        "slug": n["slug"],
        "layer": n["layer"],
        "kind": "component",
        "title": n["title"],
        "summary": n["summary"],
        "status": "designed",
        "pos_x": pos[n["slug"]][0],
        "pos_y": pos[n["slug"]][1],
    } for n in nodes]
    edge_rows = [{"project_id": pid, "source": s, "target": t} for s, t in edges]
    task_rows = [{
        "project_id": pid,
        "node_id": t["node"],
        "title": t["title"],
        "status": "todo",
        "approval_state": "none",
        "priority": i,
    } for i, t in enumerate(tasks)]
    retry(lambda: pod.records.bulk_create("nodes", node_rows))
    if edge_rows:
        retry(lambda: pod.records.bulk_create("edges", edge_rows))
    if task_rows:
        retry(lambda: pod.records.bulk_create("tasks", task_rows))
    return pid


# ---------- re-tidy an existing project's layout ----------
def relayout_project(pod, project_id: str):
    """Recompute + persist node positions for a project (the canvas "Tidy" action).
    Single source of truth for layout, shared with generation."""
    nodes = list_all(pod, "nodes", project_id=project_id)
    edges = list_all(pod, "edges", project_id=project_id)
    edge_pairs = [(e.get("source"), e.get("target")) for e in edges]
    node_lite = [{"slug": n.get("slug"), "layer": n.get("layer") or "api"} for n in nodes]
    pos = layout(node_lite, edge_pairs)
    updates = [{"id": n["id"], "pos_x": pos[n["slug"]][0], "pos_y": pos[n["slug"]][1]}
               for n in nodes if n.get("slug") in pos]
    if updates:
        retry(lambda: pod.records.bulk_update("nodes", updates))
    return len(updates)


# ---------- orchestration ----------
# A generator that yields {"stage", ...} progress events as it works, ending with a
# {"stage":"done", ...} carrying the result. The whole pipeline takes minutes (two
# LLM passes), so streaming these stages is what lets the UI show real progress and
# lets the client abort: if it disconnects, the consumer stops pulling and no later
# stage (including the persist) runs.
def generate_steps(pod, prompt: str, name: str | None = None):
    name = name or " ".join(prompt.split()[:6])[:60]

    yield {"stage": "grounding"}
    guidance = ground(pod, prompt)
    yield {"stage": "grounded", "chars": len(guidance)}

    # SINGLE agent pass: ask for the full map AND the first build tasks at once.
    # This used to be two sequential passes (decompose, then refine + tasks), which
    # roughly doubled the wall-clock time. The local normalize() below already
    # repairs the graph into a valid DAG and back-fills tasks, so the second LLM
    # round-trip was redundant — dropping it ~halves generation time with no node cap.
    yield {"stage": "decompose"}
    reply = ask(pod, (
        "You are a senior software architect. Using the GUIDANCE below, decompose the "
        "product idea into a FOCUSED system map AND its first build tasks in a SINGLE pass. "
        "Cover the CORE components across the relevant layers (client, api, data, "
        "integration, infra) — aim for about 8–14 nodes, the ones that matter, no filler. "
        "Keep every summary to ONE short clause.\n"
        "Output EXACTLY two parts and nothing else:\n"
        "1) a ```json fenced block of shape:\n"
        '{"nodes":[{"id":"kebab-slug","layer":"client|api|data|integration|infra",'
        '"title":"short name","summary":"one clear sentence"}],'
        '"edges":[{"source":"id","target":"id"}],'
        '"tasks":[{"node":"id","title":"first concrete build task"}]}\n'
        "   Rules: an edge means target depends on source; ids unique kebab-case; the graph "
        "MUST be a DAG (no cycles) and fully connected (no orphans); exactly 1 task per node.\n"
        "2) a markdown section starting with `## Build Summary`: a one-line overview, then "
        "one bullet per node `- **title** (layer) — what it does`, then a `Build first:` line.\n"
        f"\nIDEA: {prompt}\n\nGUIDANCE:\n{guidance}"
    ), title="generate-architecture")
    graph, summary_md = split_reply(reply)
    yield {"stage": "decomposed",
           "nodes": len(graph.get("nodes", [])), "edges": len(graph.get("edges", []))}

    # local pass: normalize layers, repair cycles into a DAG, back-fill tasks (no LLM call)
    yield {"stage": "refine"}
    nodes, edges, dropped, tasks = normalize(graph)
    assert nodes, "no nodes produced"
    assert is_dag({n["slug"] for n in nodes}, edges), "graph still cyclic after repair"

    yield {"stage": "persisting",
           "nodes": len(nodes), "edges": len(edges), "tasks": len(tasks)}
    pid = persist(pod, name, prompt, nodes, edges, tasks, summary_md)
    yield {"stage": "done", "project_id": pid, "nodes": nodes, "edges": edges,
           "tasks": tasks, "summary_md": summary_md}


def generate_architecture(pod, prompt: str, name: str | None = None):
    """Blocking convenience wrapper (CLI + non-streaming route) over generate_steps."""
    done = None
    for ev in generate_steps(pod, prompt, name):
        if ev["stage"] == "done":
            done = ev
        else:
            print(f"• {ev['stage']}" + (f" { {k: v for k, v in ev.items() if k != 'stage'} }"
                                         if len(ev) > 1 else ""))
    assert done, "generation produced no result"
    return (done["project_id"], done["nodes"], done["edges"],
            done["tasks"], done["summary_md"])


# ======================================================================
# inlined from backend/lemma-map/guide_node.py
# ======================================================================


# backend/lemma-map/guide_node.py — Step 4: per-node, RAG-grounded build guidance
# Run: source .venv/bin/activate && python lemma-map/guide_node.py [project_id] [node_slug] [question...]
#
# {project_id, node_id(=slug), question?} -> Guidance. Grounded by /knowledge,
# appended to node_threads, cached by qhash so re-asking the same question is a
# free read (the brief's "work that picks up again tomorrow").
#
# STATUS: built + compiles; UNVERIFIED end-to-end (Cloud was down at build time).


DEFAULT_QUESTION = "How do I build this node? Give concrete, ordered first steps."


def _qhash(node_id: str, question: str) -> str:
    norm = " ".join(question.split()).lower()
    return hashlib.sha256(f"{node_id}|{norm}".encode()).hexdigest()[:16]


def _upstream(pod, project_id: str, slug: str) -> list[str]:
    """Titles of the nodes this node depends on (inbound edges target==slug)."""
    edges = list_all(pod, "edges", project_id=project_id)
    sources = [e["source"] for e in edges if e.get("target") == slug]
    if not sources:
        return []
    nodes = list_all(pod, "nodes", project_id=project_id)
    by_slug = {n.get("slug"): n for n in nodes}
    return [by_slug[s]["title"] for s in sources if s in by_slug]


def _cached_thread(pod, project_id: str, slug: str, qhash: str):
    rows = retry(lambda: pod.records.list("node_threads", limit=200, filter=[
        {"field": "project_id", "op": "eq", "value": project_id},
        {"field": "node_id", "op": "eq", "value": slug},
        {"field": "qhash", "op": "eq", "value": qhash},
    ])).to_dict()["items"]
    return rows[0] if rows else None


def guide_node(pod, project_id: str, node_id: str, question: str | None = None,
               *, refresh: bool = False) -> dict:
    question = (question or DEFAULT_QUESTION).strip()
    qhash = _qhash(node_id, question)

    if not refresh:
        hit = _cached_thread(pod, project_id, node_id, qhash)
        if hit:
            sources = hit.get("sources") or {}
            return {
                "cached": True,
                "thread_id": hit.get("id"),
                "node_id": node_id,
                "question": question,
                "guidance_md": hit.get("answer") or "",
                "structured": (sources or {}).get("structured", {}),
                "sources": (sources or {}).get("paths", []),
            }

    node = find_node(pod, project_id, node_id)
    if not node:
        raise ValueError(f"node '{node_id}' not found in project {project_id}")
    title = node.get("title") or node_id
    layer = node.get("layer") or "api"
    summary = node.get("summary") or ""
    deps = _upstream(pod, project_id, node_id)

    context, paths = search_knowledge(pod, [
        f"how to build {title} in the {layer} layer",
        question,
        f"best practices, steps and tech for a {layer} component",
    ], budget=1600)

    reply = ask(pod, (
        "You are a senior build coach for a solo founder. Give concrete, grounded, "
        "buildable guidance for ONE node of their system — not a lecture. Use the "
        "GUIDANCE excerpts where relevant; do not invent facts about their stack.\n"
        "Output EXACTLY two parts and nothing else:\n"
        "1) a ```json fenced block of shape:\n"
        '{"steps":["ordered, imperative build steps"],'
        '"checklist":["done-when checks"],'
        '"watch_out":["common mistakes / blockers"],'
        '"tech":["concrete tools or libraries to use"]}\n'
        "   Keep each item one short line; include as many as the node genuinely needs.\n"
        "2) a markdown section starting with `## How to build " + title + "`: a one-line "
        "framing, then the steps as a numbered list, then a short `Done when:` line.\n\n"
        f"NODE: {title} (layer: {layer})\n"
        f"WHAT IT IS: {summary}\n"
        f"DEPENDS ON (must exist first): {', '.join(deps) or 'nothing — this is a foundation node'}\n"
        f"FOUNDER ASKS: {question}\n\n"
        f"GUIDANCE:\n{context}"
    ), title=f"guide-{node_id}")

    structured, guidance_md = split_reply(reply)

    thread = retry(lambda: pod.records.create("node_threads", {
        "project_id": project_id,
        "node_id": node_id,
        "question": question,
        "answer": guidance_md,
        "sources": {"paths": paths, "structured": structured},
        "qhash": qhash,
    }))

    return {
        "cached": False,
        "thread_id": thread.get("id"),
        "node_id": node_id,
        "question": question,
        "guidance_md": guidance_md,
        "structured": structured,
        "sources": paths,
    }


def _pick_demo_target(pod):
    """For the no-arg CLI: newest project + a sensible 'build-first' node."""
    projects = retry(lambda: pod.records.list(
        "projects", limit=50, sort=[{"field": "created_at", "direction": "desc"}]
    )).to_dict()["items"]
    if not projects:
        raise SystemExit("no projects yet — run generate_architecture.py first")
    pid = projects[0]["id"]
    nodes = list_all(pod, "nodes", project_id=pid)
    if not nodes:
        raise SystemExit(f"project {pid} has no nodes")
    edges = list_all(pod, "edges", project_id=pid)
    has_upstream = {e.get("target") for e in edges}
    foundation = next((n for n in nodes if n.get("slug") not in has_upstream), nodes[0])
    return pid, foundation.get("slug")


# ======================================================================
# inlined from backend/lemma-map/approvals.py
# ======================================================================


# backend/lemma-map/approvals.py — Step 5a: the approval spine (design-lock + gate)
# Run: source .venv/bin/activate && python lemma-map/approvals.py [project_id] [lock|unlock|status]
#
# The brief's "the unlock is approvals." We model approval as FIRST-CLASS RECORD
# STATE, not an agent-tool approval: a human gating a project lifecycle transition
# (input -> state -> action -> APPROVAL -> outcome). Locking the design flips every
# node designed->building and every seed task none->approved, and is the gate the
# export/outcome step requires.
#
# STATUS: built + compiles; UNVERIFIED end-to-end (Cloud was down at build time).


NODE_STATUSES = {"designed", "building", "blocked", "done"}


def _project(pod, project_id: str) -> dict:
    proj = retry(lambda: pod.records.get("projects", project_id))
    if not proj:
        raise ValueError(f"project {project_id} not found")
    return proj


def lock_design(pod, project_id: str, approver: str = "founder") -> dict:
    """Approve the design: lock it, move designed nodes into building, approve seed tasks."""
    proj = _project(pod, project_id)
    if proj.get("design_locked"):
        return {"already_locked": True, "project_id": project_id}

    nodes = list_all(pod, "nodes", project_id=project_id)
    to_build = [{"id": n["id"], "status": "building"}
                for n in nodes if n.get("status") == "designed"]
    tasks = list_all(pod, "tasks", project_id=project_id)
    to_approve = [{"id": t["id"], "approval_state": "approved"}
                  for t in tasks if t.get("approval_state") in (None, "none")]

    if to_build:
        retry(lambda: pod.records.bulk_update("nodes", to_build))
    if to_approve:
        retry(lambda: pod.records.bulk_update("tasks", to_approve))
    retry(lambda: pod.records.update("projects", project_id, {"design_locked": True}))

    return {
        "project_id": project_id,
        "design_locked": True,
        "approved_by": approver,
        "nodes_moved_to_building": len(to_build),
        "tasks_approved": len(to_approve),
    }


def unlock_design(pod, project_id: str) -> dict:
    """Reverse a lock (for demo re-runs): building->designed, approved->none."""
    _project(pod, project_id)
    nodes = list_all(pod, "nodes", project_id=project_id)
    revert_nodes = [{"id": n["id"], "status": "designed"}
                    for n in nodes if n.get("status") == "building"]
    tasks = list_all(pod, "tasks", project_id=project_id)
    revert_tasks = [{"id": t["id"], "approval_state": "none"}
                    for t in tasks if t.get("approval_state") == "approved"]
    if revert_nodes:
        retry(lambda: pod.records.bulk_update("nodes", revert_nodes))
    if revert_tasks:
        retry(lambda: pod.records.bulk_update("tasks", revert_tasks))
    retry(lambda: pod.records.update("projects", project_id, {"design_locked": False}))
    return {"project_id": project_id, "design_locked": False,
            "nodes_reverted": len(revert_nodes), "tasks_reverted": len(revert_tasks)}


def require_design_lock(pod, project_id: str) -> dict:
    """Gate used by outcomes (export/digest-send). Raises if design isn't approved."""
    proj = _project(pod, project_id)
    if not proj.get("design_locked"):
        raise PermissionError(
            "design not locked — approve the design (lock_design) before this action"
        )
    return proj


def set_node_status(pod, project_id: str, slug: str, status: str) -> dict:
    """Move one node along designed->building->blocked->done."""
    status = (status or "").strip().lower()
    if status not in NODE_STATUSES:
        raise ValueError(f"status must be one of {sorted(NODE_STATUSES)}")
    rows = retry(lambda: pod.records.list("nodes", limit=1, filter=[
        {"field": "project_id", "op": "eq", "value": project_id},
        {"field": "slug", "op": "eq", "value": slug},
    ])).to_dict()["items"]
    if not rows:
        raise ValueError(f"node '{slug}' not found in project {project_id}")
    updated = retry(lambda: pod.records.update("nodes", rows[0]["id"], {"status": status}))
    return {"node_id": slug, "status": updated.get("status", status)}


# ======================================================================
# inlined from backend/lemma-map/export_repo.py
# ======================================================================


# backend/lemma-map/export_repo.py — Step 5b: approval-gated repo scaffold (BYO token)
# Run: source .venv/bin/activate && python lemma-map/export_repo.py [project_id]            # dry-run, safe
#      GITHUB_TOKEN=ghp_xxx python lemma-map/export_repo.py [project_id] --push owner reponame
#
# The "outcome" half of the loop: turn the approved system map into a real repo
# scaffold (README + architecture doc + ordered backlog + per-layer stubs). There
# is NO Lemma GitHub connector, so we hit the GitHub REST API directly with the
# founder's own token. GATED on design-lock and DRY-RUN BY DEFAULT — it never
# touches GitHub unless you explicitly pass --push and a token.
#
# STATUS: built + compiles; dry-run manifest is pure-local. The --push path is
# UNVERIFIED (needs a real token + a live pod) — clearly fenced behind the flag.



LAYER_ORDER = ("infra", "data", "integration", "api", "client")


def _slugify(name: str) -> str:
    keep = [c.lower() if c.isalnum() else "-" for c in name.strip()]
    out = "".join(keep)
    while "--" in out:
        out = out.replace("--", "-")
    return out.strip("-") or "forge-project"


def build_scaffold(pod, project_id: str) -> list[dict]:
    """Return a list of {path, content} files — the repo scaffold, computed locally."""
    proj = retry(lambda: pod.records.get("projects", project_id))
    nodes = list_all(pod, "nodes", project_id=project_id)
    edges = list_all(pod, "edges", project_id=project_id)
    tasks = sorted(list_all(pod, "tasks", project_id=project_id),
                   key=lambda t: t.get("priority", 0))
    name = proj.get("name") or "Forge Project"
    by_slug = {n.get("slug"): n for n in nodes}

    readme = [f"# {name}\n", proj.get("summary") or proj.get("prompt") or "", "",
              "## Getting started", "1. Read `docs/ARCHITECTURE.md` for the system map.",
              "2. Work `BACKLOG.md` top-to-bottom — it's in dependency order.",
              "", "_Scaffolded by Forge._\n"]

    arch = [f"# Architecture — {name}\n"]
    for layer in LAYER_ORDER:
        layer_nodes = [n for n in nodes if n.get("layer") == layer]
        if not layer_nodes:
            continue
        arch.append(f"\n## {layer.capitalize()}\n")
        for n in layer_nodes:
            arch.append(f"- **{n.get('title')}** (`{n.get('slug')}`) — {n.get('summary') or ''}")
    arch.append("\n## Dependencies\n")
    for e in edges:
        s, t = by_slug.get(e.get("source")), by_slug.get(e.get("target"))
        if s and t:
            arch.append(f"- {t.get('title')} depends on {s.get('title')}")

    backlog = [f"# Backlog — {name}\n", "Ordered by build priority.\n"]
    for t in tasks:
        node = by_slug.get(t.get("node_id"))
        where = f" _(node: {node.get('title')})_" if node else ""
        backlog.append(f"- [ ] {t.get('title')}{where}")

    files = [
        {"path": "README.md", "content": "\n".join(readme)},
        {"path": "docs/ARCHITECTURE.md", "content": "\n".join(arch)},
        {"path": "BACKLOG.md", "content": "\n".join(backlog)},
        {"path": ".gitignore", "content": "node_modules/\n.venv/\n__pycache__/\n.env\n"},
    ]
    # one placeholder per layer that actually has nodes, so the tree mirrors the map
    for layer in LAYER_ORDER:
        if any(n.get("layer") == layer for n in nodes):
            members = [n.get("title") for n in nodes if n.get("layer") == layer]
            files.append({
                "path": f"src/{layer}/README.md",
                "content": f"# {layer.capitalize()}\n\nComponents:\n"
                           + "\n".join(f"- {m}" for m in members) + "\n",
            })
    return files


# ---------- GitHub REST (only reached behind --push + a token) ----------
def _gh(token: str) -> httpx.Client:
    return httpx.Client(
        base_url="https://api.github.com",
        headers={"Authorization": f"Bearer {token}",
                 "Accept": "application/vnd.github+json",
                 "X-GitHub-Api-Version": "2022-11-28"},
        timeout=30.0,
    )


def push_to_github(files: list[dict], *, token: str, owner: str, repo: str,
                   private: bool = True, description: str = "") -> dict:
    """Create the repo and commit every scaffold file. Outward-facing — explicit only."""
    with _gh(token) as gh:
        r = gh.post("/user/repos", json={
            "name": repo, "private": private, "auto_init": False,
            "description": description[:300],
        })
        if r.status_code not in (201, 422):  # 422 == already exists; we proceed to write
            r.raise_for_status()
        for f in files:
            put = gh.put(f"/repos/{owner}/{repo}/contents/{f['path']}", json={
                "message": f"forge: add {f['path']}",
                "content": base64.b64encode(f["content"].encode()).decode(),
            })
            put.raise_for_status()
    return {"repo_url": f"https://github.com/{owner}/{repo}", "files_written": len(files)}


def export_repo(pod, project_id: str, *, token: str | None = None,
                owner: str | None = None, repo: str | None = None,
                private: bool = True, push: bool = False) -> dict:
    proj = require_design_lock(pod, project_id)  # GATE: design must be approved
    files = build_scaffold(pod, project_id)
    if not push:
        return {"pushed": False, "file_count": len(files),
                "files": [f["path"] for f in files],
                "manifest": files}
    token = token or os.getenv("GITHUB_TOKEN")
    if not (token and owner):
        raise ValueError("push requires a GITHUB_TOKEN and an owner")
    repo = repo or _slugify(proj.get("name") or project_id)
    result = push_to_github(files, token=token, owner=owner, repo=repo,
                            private=private, description=proj.get("name") or "")
    return {"pushed": True, **result}


# ======================================================================
# inlined from backend/lemma-map/digest.py
# ======================================================================


# backend/lemma-map/digest.py — Step 5c: the recurring build digest (outcome)
# Run: source .venv/bin/activate && python lemma-map/digest.py [project_id]
#
# Closes the loop with a standing signal: "what shipped, what's blocked, what's
# next." Primary path is ON-DEMAND (compute state -> agent writes the digest).
# Sending it (Slack/Gmail connector) and a daily Lemma schedule are optional and
# degrade gracefully per the plan — dry-run by default, nothing is sent or
# scheduled unless asked.
#
# STATUS: built + compiles; on-demand digest UNVERIFIED end-to-end (Cloud down at
# build time). The schedule payload shape is a best-effort guess — confirm against
# the live /scalar docs before relying on it.



def compute_state(pod, project_id: str) -> dict:
    """Pure record read -> operating state. No LLM; this is the ground truth."""
    nodes = list_all(pod, "nodes", project_id=project_id)
    edges = list_all(pod, "edges", project_id=project_id)
    tasks = list_all(pod, "tasks", project_id=project_id)
    by_slug = {n.get("slug"): n for n in nodes}
    done = {s for s, n in by_slug.items() if n.get("status") == "done"}
    upstreams: dict[str, list[str]] = {}
    for e in edges:
        upstreams.setdefault(e.get("target"), []).append(e.get("source"))

    def title(slug):
        return (by_slug.get(slug) or {}).get("title", slug)

    shipped, in_progress, blocked, ready = [], [], [], []
    for slug, n in by_slug.items():
        st = n.get("status")
        ups = upstreams.get(slug, [])
        ups_done = all(u in done for u in ups)
        if st == "done":
            shipped.append(title(slug))
        elif st == "blocked" or (st in ("designed", "building") and not ups_done):
            missing = [title(u) for u in ups if u not in done]
            blocked.append({"node": title(slug),
                            "waiting_on": missing or ["(marked blocked)"]})
        elif st == "building":
            in_progress.append(title(slug))
        elif st == "designed" and ups_done:
            ready.append(title(slug))

    return {
        "node_count": len(nodes),
        "shipped": shipped,
        "in_progress": in_progress,
        "blocked": blocked,
        "ready_next": ready,
        "open_tasks": sum(1 for t in tasks if t.get("status") != "done"),
    }


def build_digest(pod, project_id: str) -> dict:
    proj = retry(lambda: pod.records.get("projects", project_id))
    state = compute_state(pod, project_id)
    reply = ask(pod, (
        "You are a build operations assistant. Write a SHORT daily build digest for a "
        "solo founder from the STATE below — encouraging but honest, no fluff.\n"
        "Output EXACTLY two parts and nothing else:\n"
        "1) a ```json fenced block: "
        '{"shipped":[...],"in_progress":[...],"blocked":[{"node":"...","waiting_on":"..."}],'
        '"build_next":[...],"headline":"one line"}\n'
        "2) a markdown section `## Daily Build Digest` — headline, then short "
        "**Shipped / In progress / Blocked / Build next** subsections (omit empty ones).\n\n"
        f"PROJECT: {proj.get('name')}\n"
        f"STATE: {state}"
    ), title="build-digest")
    structured, digest_md = split_reply(reply)
    return {"project_id": project_id, "state": state,
            "structured": structured, "digest_md": digest_md}


def send_digest(pod, project_id: str, *, auth_config: str | None = None,
                operation: str | None = None, payload: dict | None = None,
                account_id: str | None = None, dry_run: bool = True) -> dict:
    """Build the digest and (optionally) send it through a Slack/Gmail connector.

    dry_run=True (default) returns the digest without sending — the graceful
    fallback the plan calls for if connectors are immature.
    """
    digest = build_digest(pod, project_id)
    if dry_run or not (auth_config and operation):
        return {"sent": False, **digest}
    body = dict(payload or {})
    body.setdefault("text", digest["digest_md"])
    result = retry(lambda: pod.connectors.execute(
        auth_config, operation, body, account_id=account_id
    ))
    return {"sent": True, "delivery": getattr(result, "to_dict", lambda: result)(), **digest}


def register_daily_schedule(pod, project_id: str, *, cron: str = "0 13 * * *",
                            agent: str = "hello") -> dict:
    """OPTIONAL: ask Lemma to run the digest daily. UNVERIFIED payload shape —
    confirm CreateScheduleRequest fields against the live /scalar docs first."""
    from lemma_sdk.openapi_client.models.create_schedule_request import (
        CreateScheduleRequest,
    )
    payload = {
        "name": f"forge-digest-{project_id[:8]}",
        "schedule_type": "CRON",
        "cron_expression": cron,
        "agent_name": agent,
        "is_active": True,
        "message": f"Write today's Forge build digest for project {project_id}.",
    }
    created = retry(lambda: pod.schedules.create(CreateScheduleRequest.from_dict(payload)))
    return {"scheduled": True, "id": str(getattr(created, "id", "?")), "cron": cron}


# ======================================================================
# Forge API dispatcher (ported from backend/main.py routes)
# ======================================================================
_ARCH_LAYERS = ("client", "api", "data", "integration", "infra")


def _node_slug(text):
    s = re.sub(r"[^a-z0-9]+", "-", (text or "").strip().lower()).strip("-")
    return s or "node"


def _unique_node_slug(text, existing):
    base = _node_slug(text)
    slug, i = base, 2
    while slug in existing:
        slug, i = f"{base}-{i}", i + 1
    return slug


def _rf_nodes(nodes):
    return [{
        "id": n.get("slug"),
        "type": "forge",
        "position": {"x": n.get("pos_x") or 0.0, "y": n.get("pos_y") or 0.0},
        "data": {
            "slug": n.get("slug"), "title": n.get("title"), "summary": n.get("summary"),
            "layer": n.get("layer"), "kind": n.get("kind"), "status": n.get("status"),
        },
    } for n in nodes]


def _rf_edges(edges):
    out = []
    for e in edges:
        s, t = e.get("source"), e.get("target")
        out.append({"id": e.get("id") or f"{s}->{t}", "source": s, "target": t})
    return out


def _load_project(pod, project_id):
    proj = retry(lambda: pod.records.get("projects", project_id))
    if not proj:
        raise ValueError(f"project {project_id} not found")
    nodes = list_all(pod, "nodes", project_id=project_id)
    edges = list_all(pod, "edges", project_id=project_id)
    tasks = sorted(list_all(pod, "tasks", project_id=project_id),
                   key=lambda t: t.get("priority", 0))
    return {
        "project": {"id": proj.get("id"), "name": proj.get("name"),
                    "status": proj.get("status"),
                    "design_locked": proj.get("design_locked"),
                    "summary": proj.get("summary"), "prompt": proj.get("prompt")},
        "graph": {"nodes": _rf_nodes(nodes), "edges": _rf_edges(edges)},
        "tasks": tasks,
    }


class ForgeApiInput(BaseModel):
    action: str
    project_id: str | None = None
    node_id: str | None = None
    slug: str | None = None
    question: str | None = None
    refresh: bool = False
    status: str | None = None
    name: str | None = None
    prompt: str | None = None
    layer: str | None = None
    kind: str | None = None
    title: str | None = None
    summary: str | None = None
    pos_x: float | None = None
    pos_y: float | None = None
    source: str | None = None
    target: str | None = None
    edge_id: str | None = None
    push: bool = False
    owner: str | None = None
    repo: str | None = None


class ForgeApiResult(BaseModel):
    ok: bool = True
    error: str | None = None
    code: int | None = None
    data: Any = None


def _dispatch(pod, d: "ForgeApiInput"):
    a = d.action
    if a == "projects":
        items = retry(lambda: pod.records.list(
            "projects", limit=100,
            sort=[{"field": "created_at", "direction": "desc"}])).to_dict()["items"]
        return {"projects": [{
            "id": p.get("id"), "name": p.get("name"), "status": p.get("status"),
            "design_locked": p.get("design_locked"), "created_at": p.get("created_at"),
        } for p in items]}
    if a == "project":
        return _load_project(pod, d.project_id)
    if a == "guidance":
        return guide_node(pod, d.project_id, d.node_id, d.question, refresh=d.refresh)
    if a == "node_status":
        return set_node_status(pod, d.project_id, d.node_id or d.slug, d.status)
    if a == "lock":
        return lock_design(pod, d.project_id)
    if a == "unlock":
        return unlock_design(pod, d.project_id)
    if a == "export":
        return export_repo(pod, d.project_id, owner=d.owner, repo=d.repo, push=d.push)
    if a == "digest":
        return build_digest(pod, d.project_id)
    if a == "create_project":
        proj = retry(lambda: pod.records.create("projects", {
            "name": d.name or "Untitled", "prompt": d.prompt or "",
            "status": "active", "design_locked": False, "summary": ""}))
        return {"project": {
            "id": proj.get("id"), "name": proj.get("name"), "status": proj.get("status"),
            "design_locked": proj.get("design_locked"), "created_at": proj.get("created_at")}}
    if a == "create_node":
        layer = (d.layer or "api").lower()
        if layer not in _ARCH_LAYERS:
            layer = "api"
        existing = {n.get("slug") for n in list_all(pod, "nodes", project_id=d.project_id)}
        slug = _unique_node_slug(d.title or d.kind or "node", existing)
        row = retry(lambda: pod.records.create("nodes", {
            "project_id": d.project_id, "slug": slug, "layer": layer,
            "kind": d.kind or "component", "title": d.title or slug,
            "summary": d.summary or "", "status": "designed",
            "pos_x": d.pos_x or 0.0, "pos_y": d.pos_y or 0.0}))
        return {"node": _rf_nodes([row])[0]}
    if a == "update_node":
        slug = d.slug or d.node_id
        rows = retry(lambda: pod.records.list("nodes", limit=1, filter=[
            {"field": "project_id", "op": "eq", "value": d.project_id},
            {"field": "slug", "op": "eq", "value": slug}])).to_dict()["items"]
        if not rows:
            raise ValueError(f"node '{slug}' not found in project {d.project_id}")
        patch = {}
        for f in ("title", "summary", "layer", "status", "pos_x", "pos_y"):
            v = getattr(d, f)
            if v is not None:
                patch[f] = v
        if patch.get("layer") and patch["layer"] not in _ARCH_LAYERS:
            patch["layer"] = "api"
        row = rows[0] if not patch else retry(
            lambda: pod.records.update("nodes", rows[0]["id"], patch))
        return {"node": _rf_nodes([row])[0]}
    if a == "delete_node":
        slug = d.slug or d.node_id
        nodes = list_all(pod, "nodes", project_id=d.project_id)
        target = next((n for n in nodes if n.get("slug") == slug), None)
        if not target:
            raise ValueError(f"node '{slug}' not found in project {d.project_id}")
        edges = list_all(pod, "edges", project_id=d.project_id)
        edge_ids = [e["id"] for e in edges
                    if e.get("source") == slug or e.get("target") == slug]
        tasks = list_all(pod, "tasks", project_id=d.project_id)
        task_ids = [t["id"] for t in tasks if t.get("node_id") == slug]
        if edge_ids:
            retry(lambda: pod.records.bulk_delete("edges", edge_ids))
        if task_ids:
            retry(lambda: pod.records.bulk_delete("tasks", task_ids))
        retry(lambda: pod.records.delete("nodes", target["id"]))
        return {"deleted": slug, "edges_removed": len(edge_ids),
                "tasks_removed": len(task_ids)}
    if a == "create_edge":
        s, t = (d.source or "").strip(), (d.target or "").strip()
        if not s or not t or s == t:
            raise ValueError("edge needs distinct source and target")
        slugs = {n.get("slug") for n in list_all(pod, "nodes", project_id=d.project_id)}
        if s not in slugs or t not in slugs:
            raise ValueError("both edge endpoints must be existing nodes")
        edges = list_all(pod, "edges", project_id=d.project_id)
        pairs = [(e.get("source"), e.get("target")) for e in edges]
        if (s, t) in pairs:
            raise ValueError("edge already exists")
        if not is_dag(slugs, pairs + [(s, t)]):
            raise ValueError("that connection would create a cycle")
        row = retry(lambda: pod.records.create(
            "edges", {"project_id": d.project_id, "source": s, "target": t}))
        return {"edge": _rf_edges([row])[0]}
    if a == "delete_edge":
        retry(lambda: pod.records.delete("edges", d.edge_id))
        return {"deleted": d.edge_id}
    if a == "relayout":
        relayout_project(pod, d.project_id)
        return _load_project(pod, d.project_id)
    raise ValueError(f"unknown action: {a}")


async def forge_api(ctx: FunctionContext, data: ForgeApiInput) -> ForgeApiResult:
    pod = Pod.from_env()
    try:
        configure_timeout(pod)
    except Exception:  # noqa: BLE001 — internals may differ in the function runtime
        pass
    try:
        return ForgeApiResult(ok=True, data=_dispatch(pod, data))
    except PermissionError as e:
        return ForgeApiResult(ok=False, error=str(e), code=409)
    except ValueError as e:
        return ForgeApiResult(ok=False, error=str(e), code=400)
    except Exception as e:  # noqa: BLE001
        return ForgeApiResult(ok=False, error=f"{type(e).__name__}: {e}", code=500)
